# -*- coding: utf-8 -*-
"""CSIS312_Airline_110524 - Sentiment Analysis on Airline Tweets

Automatically generated by Colab.

AUTHOR: Faith Paule
DATE:

PROGRAM: Airline Sentiment Analysis
TOPIC: Natural Language Processing - Sentiment Analysis, Text Classification

IDENTIFICATION: Building a sentiment analysis pipeline for airline tweets to classify sentiments (positive, neutral, negative) using three different machine learning algorithms: Naive Bayes, Logistic Regression, and Linear SVM. The complete pipeline includes: data loading, exploratory data analysis (EDA), text preprocessing with TF-IDF vectorization, train/test split, model training, and performance evaluation.
OBJECTIVES:
1. Performance evaluation of 3 classification algorithms
2. Generate confusion matrices for each model
3. Predict sentiments for new tweets using all 3 algorithms

Programming Language: Python 3

Tech Stack:
- Pandas - Data manipulation and analysis
- Seaborn/Matplotlib - Data visualization (count plots)
- Scikit-learn (sklearn) - train_test_split, TfidfVectorizer, MultinomialNB, LogisticRegression, LinearSVC
- Google Colab - Jupyter notebook environment
"""

# ============================================================================
# PART 1: DATA LOADING AND EXPLORATORY DATA ANALYSIS
# ============================================================================
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the airline tweets dataset
df = pd.read_csv('airline_tweets.csv')

print("Dataset Shape:", df.shape)
df.head()

# 1. Sentiment distribution by airline
plt.figure(figsize=(10, 6))
sns.countplot(data=df, x='airline', hue='airline_sentiment')
plt.title('Sentiment Distribution by Airline')
plt.xticks(rotation=45)
plt.show()

# 2. Reasons for negative sentiments
plt.figure(figsize=(12, 6))
sns.countplot(data=df, x='negativereason')
plt.xticks(rotation=90)
plt.title('Reasons for Negative Sentiments')
plt.show()

# 3. Overall sentiment distribution
plt.figure(figsize=(8, 5))
sns.countplot(data=df, x='airline_sentiment')
plt.title('Overall Sentiment Distribution')
plt.show()

# Print sentiment counts
print("\nSentiment Counts:")
print(df['airline_sentiment'].value_counts())

# ============================================================================
# PART 2: DATA PREPARATION FOR MACHINE LEARNING
# ============================================================================
# Select features (tweet text) and target (sentiment)
y = df['airline_sentiment']
x = df['text']

from sklearn.model_selection import train_test_split

# Split data: 80% train, 20% test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print(f"\nTraining set size: {len(x_train)}")
print(f"Testing set size: {len(x_test)}")

# ============================================================================
# PART 3: TEXT VECTORIZATION (TF-IDF)
# ============================================================================
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF vectorizer (removes English stopwords)
tfidf = TfidfVectorizer(stop_words='english')

# Fit on training data only (prevents data leakage)
tfidf.fit(x_train)

# Transform training and testing data
X_train_tfidf = tfidf.transform(x_train)
X_test_tfidf = tfidf.transform(x_test)

print(f"\nTF-IDF Training matrix shape: {X_train_tfidf.shape}")
print(f"TF-IDF Testing matrix shape: {X_test_tfidf.shape}")

# ============================================================================
# PART 4: TRAIN THREE CLASSIFICATION MODELS
# ============================================================================
# Model 1: Naive Bayes
from sklearn.naive_bayes import MultinomialNB
nb_model = MultinomialNB()
nb_model.fit(X_train_tfidf, y_train)

# Model 2: Logistic Regression
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_train_tfidf, y_train)

# Model 3: Linear SVM
from sklearn.svm import LinearSVC
svm_model = LinearSVC(random_state=42, max_iter=2000)
svm_model.fit(X_train_tfidf, y_train)

print("\n✓ All three models trained successfully!")

# ============================================================================
# ASSESSMENT PART 1: PERFORMANCE EVALUATION
# ============================================================================
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Make predictions
y_pred_nb = nb_model.predict(X_test_tfidf)
y_pred_lr = lr_model.predict(X_test_tfidf)
y_pred_svm = svm_model.predict(X_test_tfidf)

print("\n" + "="*60)
print("MODEL PERFORMANCE EVALUATION")
print("="*60)

# Naive Bayes Results
print("\n📊 NAIVE BAYES:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_nb):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_nb))

# Logistic Regression Results
print("\n📊 LOGISTIC REGRESSION:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_lr):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_lr))

# Linear SVM Results
print("\n📊 LINEAR SVM:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_svm):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred_svm))

# ============================================================================
# ASSESSMENT PART 2: CONFUSION MATRICES
# ============================================================================
# Function to plot confusion matrix
def plot_confusion_matrix(y_true, y_pred, title, labels):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
                xticklabels=labels, yticklabels=labels)
    plt.title(f'Confusion Matrix - {title}')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()
    return cm

sentiment_labels = ['negative', 'neutral', 'positive']

print("\n" + "="*60)
print("CONFUSION MATRICES")
print("="*60)

# Plot confusion matrices for all three models
print("\n🔴 Naive Bayes Confusion Matrix:")
cm_nb = plot_confusion_matrix(y_test, y_pred_nb, 'Naive Bayes', sentiment_labels)

print("\n🟠 Logistic Regression Confusion Matrix:")
cm_lr = plot_confusion_matrix(y_test, y_pred_lr, 'Logistic Regression', sentiment_labels)

print("\n🟢 Linear SVM Confusion Matrix:")
cm_svm = plot_confusion_matrix(y_test, y_pred_svm, 'Linear SVM', sentiment_labels)

# ============================================================================
# ASSESSMENT PART 3: PREDICTION FOR NEW TWEETS
# ============================================================================
print("\n" + "="*60)
print("SENTIMENT PREDICTIONS FOR NEW TWEETS")
print("="*60)

# Sample new tweets for prediction
new_tweets = [
    "The flight was amazing! Great service and on time!",
    "Worst experience ever. Lost my luggage and staff was rude.",
    "Flight was okay, nothing special but not terrible either.",
    "I love flying with this airline! Highly recommend!",
    "Delayed again for the 3rd time. Very disappointed."
]

# Transform new tweets using the same TF-IDF vectorizer
new_tweets_tfidf = tfidf.transform(new_tweets)

# Get predictions from all three models
nb_predictions = nb_model.predict(new_tweets_tfidf)
lr_predictions = lr_model.predict(new_tweets_tfidf)
svm_predictions = svm_model.predict(new_tweets_tfidf)

# Create results DataFrame
results_df = pd.DataFrame({
    'Tweet': new_tweets,
    'Naive Bayes': nb_predictions,
    'Logistic Regression': lr_predictions,
    'Linear SVM': svm_predictions
})

print("\nPrediction Results for Sample Tweets:")
print(results_df.to_string(index=False))

# ============================================================================
# MODEL COMPARISON SUMMARY
# ============================================================================
print("\n" + "="*60)
print("MODEL COMPARISON SUMMARY")
print("="*60)

# Calculate accuracies for comparison
accuracies = {
    'Naive Bayes': accuracy_score(y_test, y_pred_nb),
    'Logistic Regression': accuracy_score(y_test, y_pred_lr),
    'Linear SVM': accuracy_score(y_test, y_pred_svm)
}

# Find best model
best_model = max(accuracies, key=accuracies.get)
best_accuracy = accuracies[best_model]

print("\nAccuracy Comparison:")
for model, acc in accuracies.items():
    print(f"  {model}: {acc:.4f}")

print(f"\n🏆 BEST MODEL: {best_model} with {best_accuracy:.4f} accuracy")

# Visualize accuracy comparison
plt.figure(figsize=(8, 5))
plt.bar(accuracies.keys(), accuracies.values(), color=['blue', 'orange', 'green'])
plt.title('Model Accuracy Comparison')
plt.xlabel('Model')
plt.ylabel('Accuracy')
plt.ylim(0, 1)
for i, (model, acc) in enumerate(accuracies.items()):
    plt.text(i, acc + 0.01, f'{acc:.4f}', ha='center')
plt.show()

print("\n✅ Assessment Complete: Performance evaluation, confusion matrices, and predictions for all 3 algorithms have been generated!")
