# -*- coding: utf-8 -*-
"""Paule_S-CSIS312LA_Finals Activity 4 - Jaccard Similarity with Stopword Removal

Automatically generated by Colab.

AUTHOR: Faith Moselle O. Paule
PROGRAM CODE: BCS35
COURSE: S-CSIS312LA
DUE DATE: November 30
TOPIC: Natural Language Processing (NLP) - Text Similarity, Stopword Removal, Jaccard Index, Text Preprocessing
ACTIVITY: Text Similarity using Jaccard Index
Building a text similarity calculator using the Jaccard Similarity Index after removing stopwords (both NLTK's default English stopwords and user-provided custom stopwords). The program tokenizes text, filters out stopwords, converts words to lowercase, and computes similarity as the ratio of intersection to union of unique words.
PROBLEM DESCRIPTION:
Compute similarity between two text strings after removing common stopwords
and optional custom stopwords using the Jaccard Similarity Index.

Programming Language: Python 3

Tech Stack:
- NLTK (Natural Language Toolkit) - stopwords corpus
- typing - Type hints (List)
- Python Standard Library - set operations (intersection, union)
- Google Colab - Jupyter notebook environment

JACCARD SIMILARITY FORMULA:
    J(A, B) = |A ∩ B| / |A ∪ B|
    
    where:
    - A = set of unique words in text1 after stopword removal
    - B = set of unique words in text2 after stopword removal
    - |A ∩ B| = number of common words
    - |A ∪ B| = total number of unique words in both texts

INPUT:
- text1, text2: Two text strings (1 ≤ length ≤ 10^4)
- custom_stopwords: List of additional stopwords (0-100 items, lowercase, no duplicates)

OUTPUT:
- Float representing Jaccard similarity score (0.0 to 1.0)
"""

import nltk
from nltk.corpus import stopwords
from typing import List

# Download NLTK stopwords (English common words)
nltk.download('stopwords')


def remove_stopwords(text: str, custom_stopwords: List[str] = []) -> set:
    """
    Remove stopwords from text and return set of unique meaningful words.
    
    Steps:
    1. Split text into words (whitespace tokenization)
    2. Get NLTK's default English stopwords
    3. Add custom stopwords to the stopword set
    4. Filter out stopwords (case-insensitive)
    5. Return set of unique filtered words
    
    Args:
        text: Input text string
        custom_stopwords: List of additional words to remove
    
    Returns:
        Set of unique words after stopword removal
    """
    # Tokenize by splitting on whitespace
    # (Assumes punctuation is separated by spaces as per problem statement)
    words = text.split()
    
    # Get NLTK's built-in English stopwords
    common_stopwords = set(stopwords.words('english'))
    
    # Combine default stopwords with custom stopwords
    stopwords_set = common_stopwords.union(set(custom_stopwords))
    
    # Filter out stopwords, convert to lowercase for case-insensitive comparison
    # Using set comprehension for O(1) lookup efficiency
    filtered_words = {word.lower() for word in words if word.lower() not in stopwords_set}
    
    return filtered_words


def calculate_jaccard_similarity(text1: str, text2: str, custom_stopwords: List[str] = []) -> float:
    """
    Calculate Jaccard similarity between two texts after stopword removal.
    
    Jaccard Similarity = |Intersection| / |Union|
    
    - Returns 1.0 if both texts have identical meaningful words
    - Returns 0.0 if both texts share no common meaningful words
    - Returns 0.0 if both texts become empty after stopword removal
    
    Args:
        text1: First text string
        text2: Second text string
        custom_stopwords: Optional list of additional stopwords
    
    Returns:
        Float similarity score between 0.0 and 1.0
    """
    # Remove stopwords from both texts
    filtered_words1 = remove_stopwords(text1, custom_stopwords)
    filtered_words2 = remove_stopwords(text2, custom_stopwords)
    
    # Compute Jaccard Similarity
    # Intersection: words that appear in BOTH texts
    intersection = filtered_words1.intersection(filtered_words2)
    
    # Union: all unique words from BOTH texts
    union = filtered_words1.union(filtered_words2)
    
    # Avoid division by zero (both texts empty after stopword removal)
    if len(union) == 0:
        return 0.0
    
    return len(intersection) / len(union)


# ============================================================================
# EXAMPLE USAGE (Provided in problem statement)
# ============================================================================
print("=" * 60)
print("EXAMPLE 1: With custom stopword 'dog'")
print("=" * 60)

text1 = "The quick brown fox jumps over the lazy dog."
text2 = "A quick brown dog jumps over the fence."
custom_stopwords = ['dog']

similarity = calculate_jaccard_similarity(text1, text2, custom_stopwords)
print(f"Text 1: {text1}")
print(f"Text 2: {text2}")
print(f"Custom stopwords: {custom_stopwords}")
print(f"Jaccard Similarity: {similarity:.4f}")

# ============================================================================
# EXAMPLE 2: Without custom stopwords
# ============================================================================
print("\n" + "=" * 60)
print("EXAMPLE 2: Without custom stopwords")
print("=" * 60)

text1 = "I am learning Natural Language Processing and it is fun."
text2 = "Learning Natural Language Processing is a lot of fun."

similarity = calculate_jaccard_similarity(text1, text2)
print(f"Text 1: {text1}")
print(f"Text 2: {text2}")
print(f"Jaccard Similarity: {similarity:.4f}")

# ============================================================================
# EXAMPLE 3: With custom stopwords
# ============================================================================
print("\n" + "=" * 60)
print("EXAMPLE 3: With custom stopwords 'simple' and 'this'")
print("=" * 60)

text1 = "This is a simple example for testing stopwords removal."
text2 = "This is another test case for stopword removal."
custom_stopwords = ['simple', 'this']

similarity = calculate_jaccard_similarity(text1, text2, custom_stopwords)
print(f"Text 1: {text1}")
print(f"Text 2: {text2}")
print(f"Custom stopwords: {custom_stopwords}")
print(f"Jaccard Similarity: {similarity:.4f}")

# ============================================================================
# ASSESSMENT: Student's own example
# ============================================================================
print("\n" + "=" * 60)
print("ASSESSMENT: Student's Example (Computer Science context)")
print("=" * 60)

text1 = "I am a third year college student in De La Salle University - Dasmariñas studying Computer Science."
text2 = "Natural Language Processing is a subject studied by Computer Science students in De La Salle University - Dasmariñas."
custom_stopwords = ['student', 'in', 'the']

print(f"Text 1: {text1}")
print(f"Text 2: {text2}")

# With custom stopwords
similarity_with_custom = calculate_jaccard_similarity(text1, text2, custom_stopwords)
print(f"\nJaccard Similarity (with custom stopwords '{custom_stopwords}'): {similarity_with_custom:.4f}")

# Without custom stopwords
similarity_without = calculate_jaccard_similarity(text1, text2)
print(f"Jaccard Similarity (without custom stopwords): {similarity_without:.4f}")

# Display word sets for insight
print("\n--- Detailed Analysis ---")
words1 = remove_stopwords(text1)
words2 = remove_stopwords(text2)
print(f"Unique words in Text 1 (after stopword removal): {words1}")
print(f"Unique words in Text 2 (after stopword removal): {words2}")
print(f"Common words: {words1.intersection(words2)}")
