# -*- coding: utf-8 -*-
"""Paule_supposed CSIS312LA_SA - N-gram Frequency Analyzer

Automatically generated by Colab.

AUTHOR: Faith Paule
PROGRAM CODE: BCS35
COURSE: S-CSIS312LA
DUE DATE: Dec 13

PROGRAM: N-gram Frequency Analysis
TOPIC: Natural Language Processing (NLP) - N-gram Analysis, Text Tokenization, Frequency Counting
DESCRIPTION: Extracts N-grams (contiguous sequences of N words) from text, counts their frequencies, filters by minimum occurrence threshold, and returns sorted results.
IDENTIFICATION: Building an N-gram frequency analyzer that extracts n-grams (contiguous sequences of N words) from text, counts their frequencies, filters by a minimum count threshold, and returns sorted results. The implementation includes tokenization (lowercase, punctuation removal), sliding window n-gram generation, frequency counting using Counter, and filtering.

Programming Language: Python 3

Tech Stack:
- re (Regular Expressions) - Tokenization with r'\b\w+\b'
- collections.Counter - Efficient frequency counting
- Python Standard Library only
- No external dependencies (no NLTK, no spaCy)

USAGE:
- Input: text (string), N (integer), min_count (integer)
- Output: Dictionary with 'ngrams' (sorted list) and 'frequency' (count dict)
"""

import re
from collections import Counter


def ngram_frequency(text: str, N: int, min_count: int):
    """
    Extract and count N-grams from text with frequency filtering.
    
    Algorithm Steps:
    1. Tokenization: Convert to lowercase, extract words using regex
    2. Sliding Window: Generate contiguous N-grams
    3. Frequency Count: Count occurrences of each N-gram
    4. Filtering: Keep only N-grams with count >= min_count
    5. Sorting: Sort by frequency (descending), then alphabetically (ascending)
    
    Args:
        text: Input text string
        N: Length of n-grams (e.g., 2 for bigrams, 3 for trigrams)
        min_count: Minimum frequency threshold (keep n-grams with count >= this)
    
    Returns:
        Dictionary containing:
        - 'ngrams': List of n-grams sorted by frequency (descending)
        - 'frequency': Dictionary mapping n-grams to their counts
    """
    
    # Step 1: Tokenization
    # \b\w+\b matches whole words (alphanumeric sequences)
    # .lower() makes everything lowercase for case-insensitive comparison
    tokens = re.findall(r'\b\w+\b', text.lower())
    
    # Step 2: Sliding Window N-gram Generation
    # Generate all contiguous sequences of length N
    # Example: tokens = ['a','b','c'], N=2 → ['a b', 'b c']
    ngrams = [' '.join(tokens[i:i+N]) for i in range(len(tokens) - N + 1)]
    
    # Step 3: Frequency Count using Counter
    # Counter automatically counts occurrences of each n-gram
    freq_count = Counter(ngrams)
    
    # Step 4: Filter N-grams by Minimum Frequency
    # Keep only n-grams that appear at least min_count times
    filtered_ngrams = {
        ngram: count 
        for ngram, count in freq_count.items() 
        if count >= min_count
    }
    
    # Step 5: Sort N-grams
    # Primary sort: frequency descending (-x[1])
    # Secondary sort: n-gram alphabetically (x[0])
    sorted_ngrams = sorted(
        filtered_ngrams.items(), 
        key=lambda x: (-x[1], x[0])
    )
    
    # Prepare result dictionary
    result = {
        'ngrams': [ngram for ngram, _ in sorted_ngrams],
        'frequency': dict(sorted_ngrams)
    }
    
    return result


# ============================================================================
# SAMPLE OUTPUT 1: Bigrams with min_count = 1 (all bigrams)
# ============================================================================
print("=" * 60)
print("SAMPLE OUTPUT 1: Bigrams (N=2, min_count=1)")
print("=" * 60)

text1 = "Python programming is fun. I love programming in Python. Programming is Python programming!"
N1 = 2
min_count1 = 1

result1 = ngram_frequency(text1, N1, min_count1)

print(f"Text: {text1}")
print(f"N: {N1}, Min Count: {min_count1}")
print(f"\nResult: {result1}")

# ============================================================================
# SAMPLE OUTPUT 2: Bigrams with min_count = 2 (only bigrams appearing ≥2 times)
# ============================================================================
print("\n" + "=" * 60)
print("SAMPLE OUTPUT 2: Bigrams (N=2, min_count=2)")
print("=" * 60)

text2 = "This is a test. This is only a test. This is a simple test."
N2 = 2
min_count2 = 2

result2 = ngram_frequency(text2, N2, min_count2)

print(f"Text: {text2}")
print(f"N: {N2}, Min Count: {min_count2}")
print(f"\nResult: {result2}")

# ============================================================================
# ADDITIONAL EXAMPLE: Trigrams
# ============================================================================
print("\n" + "=" * 60)
print("ADDITIONAL EXAMPLE: Trigrams (N=3, min_count=1)")
print("=" * 60)

text3 = "The quick brown fox jumps over the lazy dog. The quick brown fox is fast."
N3 = 3
min_count3 = 1

result3 = ngram_frequency(text3, N3, min_count3)

print(f"Text: {text3}")
print(f"N: {N3}, Min Count: {min_count3}")
print(f"\nTrigrams found: {len(result3['ngrams'])}")
print(f"Result: {result3}")
