# -*- coding: utf-8 -*-
"""Paule_CSIS312LA_SA - Finals Summative Exam: N-gram Frequency Analyzer

Automatically generated by Colab.

AUTHOR: Faith Paule
PROGRAM CODE: BCS35
COURSE: S-CSIS312LA
DUE DATE: Dec 13

EXAM TYPE: Finals Summative Exam

TOPIC: Natural Language Processing (NLP) - N-gram Analysis, Tokenization, Frequency Counting, Sliding Window Technique
PROBLEM: N-gram Frequency Analysis
IDENTIFICATION: Building an interactive N-gram frequency analyzer for a Finals Summative Exam that: tokenizes text (lowercase, punctuation removal), generates N-grams using a sliding window, counts frequencies with Counter, filters by minimum count threshold, and returns sorted results with user input integration.

In this problem, you will implement a Python function that performs the following:
  1. Tokenization: Tokenize a given input text, ignoring punctuation and handling case insensitivity.
  2. Sliding Window N-gram Generation: Generate N-grams using a sliding window technique. The N-gram size (unigram, bigram, trigram, etc.) will be provided as an input.
  3. Frequency Count: For each N-gram generated, count its frequency in the text.
  4. Filter N-grams by Frequency: The function should return only those N-grams whose frequency is above a certain threshold.

Requirements:
  1. Tokenization: You must split the input text into tokens (words), ignoring punctuation and converting all words to lowercase.
  2. Sliding Window: The N-grams should be generated using a sliding window approach. For example, if the text is "I love programming in Python", a bigram (2-gram) would generate:
    - 'I love'
    - 'love programming'
    - 'programming in'
    - 'in Python'
  3. Frequency Count: For each generated N-gram, count how many times it appears in the text.
  4. Filter by Frequency: The function should accept an additional parameter min_count which specifies the minimum frequency for an N-gram to be included in the result.

Programming Language: Python 3

Tech Stack:
- re (Regular Expressions) - Tokenization with r'\b\w+\b'
- collections.Counter - Frequency counting
- Python Standard Library only
- No external dependencies (pure Python)
"""

import re
from collections import Counter


def generate_ngrams(text: str, N: int, min_count: int):
    """
    Generate, count, and filter N-grams from input text.
    
    Args:
        text: Input text string
        N: N-gram size (1=unigram, 2=bigram, 3=trigram, etc.)
        min_count: Minimum frequency threshold for inclusion
    
    Returns:
        Dictionary with 'ngrams' (sorted list) and 'frequency' (count dictionary)
    
    Example:
        text = "I love programming in Python"
        N = 2, min_count = 1
        Returns: ngrams = ['love programming', 'programming in', 'in python', 'i love']
                 frequency = {'i love':1, 'love programming':1, ...}
    """
    
    # Step 1: Tokenization
    # \b\w+\b matches whole words (alphanumeric sequences only)
    # .lower() converts everything to lowercase (case-insensitive)
    tokens = re.findall(r'\b\w+\b', text.lower())
    
    # Step 2: Sliding Window N-gram Generation
    # Generate all contiguous sequences of length N
    # Example: tokens = ['a','b','c'], N=2 → ['a b', 'b c']
    ngrams = [' '.join(tokens[i:i+N]) for i in range(len(tokens) - N + 1)]
    
    # Step 3: Frequency Count using Counter
    # Counter automatically counts occurrences of each n-gram
    frequency = Counter(ngrams)
    
    # Step 4: Filter N-grams by Minimum Frequency
    # Keep only n-grams that appear at least min_count times
    filtered_ngrams = {
        ngram: freq 
        for ngram, freq in frequency.items() 
        if freq >= min_count
    }
    
    # Step 5: Sort N-grams
    # Primary key: frequency descending (-filtered_ngrams[x])
    # Secondary key: n-gram alphabetically (x)
    sorted_ngrams = sorted(
        filtered_ngrams.keys(), 
        key=lambda x: (-filtered_ngrams[x], x)
    )
    
    # Step 6: Prepare result dictionary
    result = {
        'ngrams': sorted_ngrams,
        'frequency': filtered_ngrams
    }
    
    return result


def print_ngrams_output(result):
    """
    Pretty print the N-gram analysis results.
    
    Args:
        result: Dictionary from generate_ngrams() with 'ngrams' and 'frequency' keys
    """
    print("\n" + "=" * 50)
    print("N-GRAM ANALYSIS RESULTS")
    print("=" * 50)
    print(f"'ngrams': {result['ngrams']}")
    print(f"'frequency': {result['frequency']}")
    print("=" * 50)


# ============================================================================
# MAIN PROGRAM - USER INTERFACE
# ============================================================================
print("=" * 50)
print("N-GRAM FREQUENCY ANALYZER")
print("=" * 50)

# Get user input
text = input("\nEnter the text: ")
N = int(input("Enter the value of N for n-grams (1=unigram, 2=bigram, 3=trigram): "))
min_count = int(input("Enter the minimum count for n-grams: "))

# Process the text and generate results
result = generate_ngrams(text, N, min_count)

# Display results
print_ngrams_output(result)

# ============================================================================
# SAMPLE RUNS (For testing)
# ============================================================================
print("\n" + "=" * 50)
print("SAMPLE EXECUTIONS")
print("=" * 50)

# Sample 1: Bigrams with min_count=1
print("\n1. Bigrams (N=2, min_count=1):")
sample_text1 = "I love programming in Python"
sample_ngrams1 = generate_ngrams(sample_text1, 2, 1)
print(f"Text: '{sample_text1}'")
print(f"Result: {sample_ngrams1}")

# Sample 2: Bigrams with min_count=2
print("\n2. Bigrams (N=2, min_count=2):")
sample_text2 = "This is a test. This is only a test. This is a simple test."
sample_ngrams2 = generate_ngrams(sample_text2, 2, 2)
print(f"Text: '{sample_text2}'")
print(f"Result: {sample_ngrams2}")

# Sample 3: Trigrams with min_count=1
print("\n3. Trigrams (N=3, min_count=1):")
sample_text3 = "The quick brown fox jumps over the lazy dog"
sample_ngrams3 = generate_ngrams(sample_text3, 3, 1)
print(f"Text: '{sample_text3}'")
print(f"Number of trigrams: {len(sample_ngrams3['ngrams'])}")
print(f"Result: {sample_ngrams3}")
