# -*- coding: utf-8 -*-
"""Paule_FActivity1 - N-gram Text Analysis Tool

Automatically generated by Colab.

AUTHOR: Faith Paule
PROGRAM CODE: BCS35
COURSE: S-CSIS312

MACHINE PROBLEM: N-grams and Text Analysis
TOPIC: Natural Language Processing (NLP) - N-gram Analysis, Text Preprocessing, Frequency Analysis
OBJECTIVE:
Implement a text analysis tool that uses n-grams to identify the most common
phrases (bigrams and trigrams) in a given text.

PROBLEM STATEMENT:
Create a Python program that analyzes given text, preprocesses it, extracts
n-grams, counts frequencies, and displays results with visualizations.

REQUIREMENTS:
1. Input Text - Allow users to input a text string
2. Preprocessing - Lowercase, remove punctuation, tokenize
3. N-gram Generation - Create bigrams (2-grams) and trigrams (3-grams)
4. Frequency Count - Count frequencies, display top 10 with counts
5. Visualization - Horizontal bar charts for top 10 n-grams

Programming Language: Python 3

Tech Stack:
- NLTK (Natural Language Toolkit) - word_tokenize, ngrams, punkt_tab tokenizer
- Collections (Counter) - Frequency counting for n-grams
- Matplotlib - Horizontal bar chart visualizations
- re (Regular Expressions) - Punctuation and special character removal
- Google Colab - Jupyter notebook environment
"""

import nltk
from collections import Counter
import matplotlib.pyplot as plt
import re

# Download the punkt tokenizer for word tokenization
nltk.download('punkt_tab')


def preprocess_text(text):
    """
    Preprocess the input text for n-gram analysis.
    
    Steps:
    1. Convert to lowercase (case-insensitive analysis)
    2. Remove punctuation and special characters (keep only words and spaces)
    3. Tokenize into individual words
    
    Args:
        text: Raw input string
    
    Returns:
        List of tokenized words
    """
    # Convert to lowercase
    text = text.lower()
    
    # Remove punctuation and special characters using regex
    # [^\w\s] matches any character that is NOT a word character or whitespace
    text = re.sub(r'[^\w\s]', '', text)
    
    # Tokenize text into individual words
    tokens = nltk.word_tokenize(text)
    
    return tokens


def generate_ngrams(tokens, n):
    """
    Generate n-grams from tokenized text.
    
    Args:
        tokens: List of tokenized words
        n: Size of n-gram (2 for bigrams, 3 for trigrams)
    
    Returns:
        List of n-gram tuples
    """
    return list(nltk.ngrams(tokens, n))


def get_top_ngrams(ngrams, top_n=10):
    """
    Count n-gram frequencies and return the most common ones.
    
    Args:
        ngrams: List of n-gram tuples
        top_n: Number of top n-grams to return (default: 10)
    
    Returns:
        List of (n-gram, frequency) tuples, sorted by frequency descending
    """
    ngram_counts = Counter(ngrams)
    return ngram_counts.most_common(top_n)


def plot_ngrams(ngrams, title):
    """
    Create a horizontal bar chart visualization of n-gram frequencies.
    
    Args:
        ngrams: List of (n-gram, frequency) tuples
        title: Chart title
    """
    # Convert n-gram tuples to space-separated strings for labels
    ngram_labels = [' '.join(gram) for gram, _ in ngrams]
    
    # Extract frequencies
    frequencies = [freq for _, freq in ngrams]
    
    # Create horizontal bar chart
    plt.figure(figsize=(10, 6))
    plt.barh(ngram_labels, frequencies, color='skyblue')
    plt.xlabel('Frequency')
    plt.ylabel('N-grams')
    plt.title(title)
    
    # Invert y-axis to show highest frequency at the top
    plt.gca().invert_yaxis()
    
    # Add frequency labels on bars
    for i, (label, freq) in enumerate(zip(ngram_labels, frequencies)):
        plt.text(freq, i, f' {freq}', va='center')
    
    plt.tight_layout()
    plt.show()


def main():
    """
    Main program execution:
    1. Get user input text
    2. Preprocess text
    3. Generate bigrams and trigrams
    4. Display top 10 with counts
    5. Generate visualizations
    """
    print("=" * 60)
    print("N-GRAM TEXT ANALYSIS TOOL")
    print("=" * 60)
    
    # Step 1: Get user input
    text = input("\nEnter your text: ")
    
    # Step 2: Preprocess text
    tokens = preprocess_text(text)
    print(f"\n✓ Preprocessed text into {len(tokens)} tokens")
    
    # Step 3: Generate n-grams
    bigrams = generate_ngrams(tokens, 2)
    trigrams = generate_ngrams(tokens, 3)
    
    print(f"✓ Generated {len(bigrams)} bigrams")
    print(f"✓ Generated {len(trigrams)} trigrams")
    
    # Step 4: Get top 10 n-grams with frequencies
    top_bigrams = get_top_ngrams(bigrams, top_n=10)
    top_trigrams = get_top_ngrams(trigrams, top_n=10)
    
    # Step 5: Display results
    print("\n" + "=" * 60)
    print("TOP 10 BIGRAMS")
    print("=" * 60)
    
    if top_bigrams:
        for i, (bigram, freq) in enumerate(top_bigrams, 1):
            bigram_str = ' '.join(bigram)
            print(f"{i:2}. '{bigram_str}': {freq} occurrence(s)")
    else:
        print("No bigrams found (text too short)")
    
    print("\n" + "=" * 60)
    print("TOP 10 TRIGRAMS")
    print("=" * 60)
    
    if top_trigrams:
        for i, (trigram, freq) in enumerate(top_trigrams, 1):
            trigram_str = ' '.join(trigram)
            print(f"{i:2}. '{trigram_str}': {freq} occurrence(s)")
    else:
        print("No trigrams found (text too short)")
    
    # Step 6: Generate visualizations (Optional requirement)
    print("\n" + "=" * 60)
    print("GENERATING VISUALIZATIONS...")
    print("=" * 60)
    
    if top_bigrams:
        plot_ngrams(top_bigrams, "Top 10 Bigrams")
    else:
        print("Not enough text for bigram visualization")
    
    if top_trigrams:
        plot_ngrams(top_trigrams, "Top 10 Trigrams")
    else:
        print("Not enough text for trigram visualization")
    
    print("\n✓ Analysis complete!")


if __name__ == "__main__":
    main()
