# -*- coding: utf-8 -*-
"""Word Sense Disambiguation (WSD)
AUTHOR: Faith Paule
DATE: 2025

IDENTIFICATION: Learning Word Sense Disambiguation (WSD) , a core Natural Language Processing (NLP) task, by implementing the Lesk Algorithm to determine which meaning of an ambiguous word (e.g., "bank") is intended based on context, using NLTK and WordNet.

Topic: Natural Language Processing (NLP) - Word Sense Disambiguation (WSD), Polysemy, Lesk Algorithm, Lexical Semantics

Programming Language: Python 3

Tech Stack:
- NLTK (Natural Language Toolkit) - WordNet corpus, tokenization, POS tagging
- WordNet - Lexical database for English (synsets, definitions)
- Google Colab - Jupyter notebook environment

Automatically generated by Colab.

LESSON OUTCOMES:
- Understand the concept of WSD and its importance in NLP
- Differentiate between knowledge-based, supervised, and unsupervised approaches
- Practice using Python libraries (NLTK, WordNet) for basic WSD
- Discuss significance of WSD in search engines, translation, and digital assistants
- Develop a simple WSD model and test its performance
"""

# ============================================================================
# THEORY SECTION: WORD SENSE DISAMBIGUATION
# ============================================================================

"""
POLYSEMY:
Words that have multiple meanings based on context.

Example: 'bank' can refer to:
- Financial institution: "I deposited money in the bank"
- River side: "We sat on the river bank"

WORD SENSE DISAMBIGUATION (WSD):
Task of identifying which meaning (sense) of a word is intended in a given context.

Applications:
- Machine Translation: Translating correct sense to avoid confusion
- Information Retrieval: Search engines provide accurate results
- Speech Recognition: Alexa/Siri understand ambiguous phrases

APPROACHES TO WSD:
1. Knowledge-based: Uses WordNet and Lesk Algorithm
2. Supervised: Trains ML models on labeled data (Naive Bayes, SVM)
3. Unsupervised: Clusters word occurrences (Latent Semantic Analysis)
"""

# ============================================================================
# SETUP: INSTALL AND DOWNLOAD NLTK RESOURCES
# ============================================================================

!pip uninstall nltk -y
!pip install nltk

import nltk

# Download WordNet (lexical database with synsets and definitions)
nltk.download('wordnet')

# Download Open Multilingual WordNet (for multiple languages)
nltk.download('omw-1.4')

# Download Punkt tokenizer (splits text into sentences/words)
nltk.download('punkt')

# Download POS tagger (identifies parts of speech)
nltk.download('averaged_perceptron_tagger')

# ============================================================================
# IMPLEMENTATION: LESK ALGORITHM (Knowledge-based WSD)
# ============================================================================

from nltk.corpus import wordnet as wn

# Sentences with the ambiguous word "bank"
sentences = [
    "The river bank was overflowing.",      # Context: river, overflowing
    "He withdrew money from the bank."      # Context: withdrew, money
]

def get_best_sense(word, context):
    """
    Manually implement Lesk Algorithm logic to select appropriate word sense.
    
    Lesk Algorithm: Compares definition overlap between context and word senses.
    The sense with most overlap is selected.
    
    Args:
        word: The ambiguous word to disambiguate
        context: The surrounding sentence
    
    Returns:
        The best matching synset (word sense)
    """
    # Get all possible senses (synsets) for the word
    synsets = wn.synsets(word)
    
    # Display all possible senses with their definitions
    print(f"\nAll possible senses for '{word}':")
    for i, syn in enumerate(synsets, 1):
        print(f"{i}. {syn.name()}: {syn.definition()}")
    
    # Lesk Algorithm logic: find sense with most context overlap
    # For demonstration, using keyword matching
    if "river" in context or "overflowing" in context:
        # Sense 0: riverbank (geographical feature)
        selected_sense = synsets[0]  # 'bank.n.01' - sloping land
    elif "money" in context or "withdrew" in context:
        # Sense 3: financial institution
        selected_sense = synsets[3]  # 'bank.n.04' - financial institution
    else:
        selected_sense = None
    
    return selected_sense


# Process each sentence
for sentence in sentences:
    # Tokenize sentence into words
    tokens = nltk.word_tokenize(sentence)
    
    # Disambiguate the word 'bank'
    best_sense = get_best_sense('bank', sentence)
    
    if best_sense:
        print(f"\n✓ Sentence: {sentence}")
        print(f"  Best sense of 'bank': {best_sense.name()}")
        print(f"  Definition: {best_sense.definition()}")
    else:
        print(f"✗ No suitable sense found for 'bank' in: {sentence}")

# ============================================================================
# EXPECTED OUTPUT:
# All possible senses for 'bank':
# 1. bank.n.01: sloping land (especially the slope beside a body of water)
# 2. bank.n.02: a financial institution that accepts deposits and channels...
# ...
# 
# ✓ Sentence: The river bank was overflowing.
#   Best sense of 'bank': bank.n.01
#   Definition: sloping land (especially the slope beside a body of water)
# 
# ✓ Sentence: He withdrew money from the bank.
#   Best sense of 'bank': bank.n.04
#   Definition: a financial institution that accepts deposits...
# ============================================================================
