# -*- coding: utf-8 -*-
"""Paule_CSIS312_102224 - NLP Preprocessing Pipeline for SMS Spam Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10feizoPtnT_Uji_d6riw44q9IGOCNUfs

STUDENT: Faith Paule
PROGRAM CODE: BCS35
COURSE: CSIS312
DATE: October 22, 2024

Topic: Natural Language Processing (NLP) - Text Preprocessing, Tokenization, Stopword Removal, Stemming

Programming Language: Python 3

IDENTIFICATION Building a complete Natural Language Processing (NLP) preprocessing pipeline for SMS spam detection. The pipeline includes: text cleaning (punctuation removal), tokenization, stopword removal, and stemming (PorterStemmer). This prepares raw text data for machine learning classification.
DESCRIPTION:
This Python script implements an NLP preprocessing pipeline for text classification.
Pipeline Steps:
1. Raw Text → 2. Text Cleaning → 3. Tokenization → 4. Stopword Removal → 
5. Stemming → 6. Ready for Vectorization/ML Algorithm

Tech Stack:
- NLTK (Natural Language Toolkit) - stopwords, PorterStemmer, punkt tokenizer
- Pandas - Data manipulation and DataFrame operations
- re (Regular Expressions) - Tokenization pattern matching
- string - Punctuation handling
- Google Colab - Jupyter notebook environment

"""

# ============================================================================
# STEP 0: IMPORT LIBRARIES AND DOWNLOAD NLTK RESOURCES
# ============================================================================
import nltk
nltk.download()  # Download NLTK resources (interactive)

import pandas as pd

# ============================================================================
# STEP 1: LOAD AND EXPLORE DATASET (SMS Spam Collection)
# ============================================================================
# Load dataset (tab-separated values, no header row)
data = pd.read_csv('smsspamcollection.tsv', sep="\t", header=None)
data.head()

# Rename columns for better readability
data.columns = ['label', 'message', 'length', 'punct']
data.head()

# Dataset statistics
print(f'Input data has {len(data)} rows, {len(data.columns)} columns')
print(f'ham (legitimate) = {len(data[data["label"]=="ham"])}')
print(f'spam = {len(data[data["label"]=="spam"])}')
print(f"Number of nulls in label: {data['label'].isnull().sum()}")
print(f"Number of nulls in message: {data['message'].isnull().sum()}")

"""
LECTURE NOTE: NLP Pipeline
Raw Text → Tokenization → Text Cleaning → Vectorization → ML Algorithm → Filter
"""

# ============================================================================
# STEP 2: TEXT CLEANING - REMOVE PUNCTUATION
# ============================================================================
import string
print(f"Punctuation to remove: {string.punctuation}")
# Output: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

def remove_punct(text):
    """Remove all punctuation characters from text."""
    text_nopunct = "".join([char for char in text if char not in string.punctuation])
    return text_nopunct

# Apply punctuation removal to the message column
data['msg_clean'] = data['message'].apply(lambda x: remove_punct(x))
data.head()

# ============================================================================
# STEP 3: TOKENIZATION - SPLIT TEXT INTO INDIVIDUAL WORDS
# ============================================================================
import re

def tokenize(text):
    """
    Split text into tokens using non-word characters as delimiters.
    \W+ matches any sequence of non-word characters (spaces, punctuation, etc.)
    """
    tokens = re.split('\W+', text)
    return tokens

# Apply tokenization to cleaned messages (convert to lowercase first)
data['msg_tokenized'] = data['msg_clean'].apply(lambda x: tokenize(x.lower()))
data.head()

# ============================================================================
# STEP 4: STOPWORD REMOVAL - FILTER OUT COMMON WORDS
# ============================================================================
nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('english')
print(f"First 10 stopwords: {stopwords[0:10]}")

def remove_stopwords(txt_tokenized):
    """Remove common stopwords from tokenized text."""
    text_clean = [word for word in txt_tokenized if word not in stopwords]
    return text_clean

# Apply stopword removal
data['msg_nosw'] = data['msg_tokenized'].apply(lambda x: remove_stopwords(x))
data.head()

# ============================================================================
# STEP 5: STEMMING - REDUCE WORDS TO ROOT FORM
# ============================================================================
from nltk.stem import PorterStemmer
ps = PorterStemmer()

# Stemming examples
print(f"Stemming examples:")
print(f"  'coder' → {ps.stem('coder')}")   # Noun
print(f"  'coding' → {ps.stem('coding')}") # Verb
print(f"  'code' → {ps.stem('code')}")     # Noun
print(f"  'data' → {ps.stem('data')}")     # Singular
print(f"  'datum' → {ps.stem('datum')}")   # Plural
print(f"  'bowl' → {ps.stem('bowl')}")
print(f"  'bowling' → {ps.stem('bowling')}")
print(f"  'bowler' → {ps.stem('bowler')}")

def stemming(tokenized_text):
    """Apply Porter stemming to each word in tokenized text."""
    text = [ps.stem(word) for word in tokenized_text]
    return text

# Apply stemming to cleaned and tokenized messages
data['msg_stemmed'] = data['msg_nosw'].apply(lambda x: stemming(x))
data.head()

"""
STEMMING SUMMARY:
The PorterStemmer library reduces words to their base or root form.
This helps group different word forms (e.g., 'run', 'running', 'ran') 
into a single feature for machine learning models.
"""
