# -*- coding: utf-8 -*-
"""Paule_FActivity2 - Tokenization in NLP with Python

Automatically generated by Colab.

AUTHOR: Faith Paule
PROGRAM CODE: BCS35
COURSE: S-CSIS312
PROGRAMMING ACTIVITY 2: Tokenization for Customer Feedback Analysis
Topic: Natural Language Processing (NLP) - Tokenization, Stopword Removal, Named Entity Recognition (NER), Text Preprocessing

IDENTIFICATION: Building a comprehensive text preprocessing and tokenization pipeline for customer feedback analysis using two NLP libraries (NLTK and spaCy). The complete implementation includes: sentence and word tokenization, stopword removal, named entity recognition (NER), and comparative analysis between NLTK and spaCy's approaches.
CASE SCENARIO:
A tech company analyzing customer feedback from surveys, social media,
and support tickets to identify common themes, opinions, and issues.

Programming Language: Python 3

OBJECTIVES:
1. Use NLTK and spaCy to tokenize customer feedback
2. Perform sentence and word tokenization
3. Remove irrelevant words (stopwords)
4. Extract named entities (product names, issues)

Tech Stack:
- NLTK (Natural Language Toolkit) - sent_tokenize, word_tokenize, stopwords corpus, punkt tokenizer
- spaCy - en_core_web_sm model, tokenization, stopword detection, named entity recognition (NER)
- Google Colab - Jupyter notebook environment
"""

# ============================================================================
# INSTALLATION AND SETUP
# ============================================================================
import nltk
import spacy

# Download NLTK resources
nltk.download('punkt')
nltk.download('stopwords')

# Load spaCy English model (run once: !python -m spacy download en_core_web_sm)
nlp = spacy.load("en_core_web_sm")

# ============================================================================
# PART 1: TOKENIZING CUSTOMER FEEDBACK
# ============================================================================
"""
Customer feedback text:
"Great product, but the software crashed twice in the last week. 
The customer support team was very helpful, though. Could improve the battery life."
"""

# Sample customer feedback
feedback_text = """Great product, but the software crashed twice in the last week. 
The customer support team was very helpful, though. Could improve the battery life."""

# ---- NLTK Tokenization ----
from nltk.tokenize import sent_tokenize, word_tokenize

def tokenize_sentences_nltk(feedback):
    """Split feedback into sentences using NLTK"""
    return sent_tokenize(feedback)

def tokenize_words_nltk(feedback):
    """Split feedback into words using NLTK"""
    return word_tokenize(feedback)

sentences_nltk = tokenize_sentences_nltk(feedback_text)
words_nltk = tokenize_words_nltk(feedback_text)

print("=" * 60)
print("PART 1: TOKENIZATION RESULTS")
print("=" * 60)
print("\nSentences (NLTK):")
for i, sent in enumerate(sentences_nltk, 1):
    print(f"  {i}. {sent}")

print(f"\nWords (NLTK): {words_nltk}")

# ---- spaCy Tokenization ----
def tokenize_words_spacy(feedback):
    """Split feedback into words using spaCy"""
    doc = nlp(feedback)
    return [token.text for token in doc]

words_spacy = tokenize_words_spacy(feedback_text)

print(f"\nWords (spaCy): {words_spacy}")

# ============================================================================
# PART 2: REMOVING STOPWORDS
# ============================================================================
print("\n" + "=" * 60)
print("PART 2: STOPWORD REMOVAL")
print("=" * 60)

# ---- NLTK Stopword Removal ----
from nltk.corpus import stopwords

def remove_stopwords_nltk(words):
    """Remove common stopwords using NLTK's stopword list"""
    stop_words = set(stopwords.words("english"))
    filtered_words = [word for word in words if word.lower() not in stop_words]
    return filtered_words

filtered_words_nltk = remove_stopwords_nltk(words_nltk)
print(f"\nFiltered Words (NLTK): {filtered_words_nltk}")

# ---- spaCy Stopword Removal ----
def remove_stopwords_spacy(feedback):
    """Remove stopwords using spaCy's token.is_stop property"""
    doc = nlp(feedback)
    filtered_words = [token.text for token in doc if not token.is_stop]
    return filtered_words

filtered_words_spacy = remove_stopwords_spacy(feedback_text)
print(f"\nFiltered Words (spaCy): {filtered_words_spacy}")

# ============================================================================
# PART 3: EXTRACTING NAMED ENTITIES
# ============================================================================
print("\n" + "=" * 60)
print("PART 3: NAMED ENTITY RECOGNITION (NER)")
print("=" * 60)

def extract_named_entities_spacy(feedback):
    """
    Extract named entities using spaCy's pre-trained NER model.
    
    Common entity labels:
    - PERSON: People's names
    - ORG: Organizations, companies
    - GPE: Countries, cities, states
    - PRODUCT: Product names
    - DATE: Dates
    """
    doc = nlp(feedback)
    entities = [(ent.text, ent.label_) for ent in doc.ents]
    return entities

named_entities = extract_named_entities_spacy(feedback_text)

print("\nNamed Entities Found:")
for entity, label in named_entities:
    print(f"  - '{entity}' → {label}")

# ============================================================================
# PART 4: COMPARATIVE ANALYSIS
# ============================================================================
print("\n" + "=" * 60)
print("PART 4: LIBRARY COMPARISON")
print("=" * 60)

# Token count comparison
print(f"\nNLTK Word Count: {len(words_nltk)}")
print(f"spaCy Word Count: {len(words_spacy)}")
print(f"NLTK Filtered Count: {len(filtered_words_nltk)}")
print(f"spaCy Filtered Count: {len(filtered_words_spacy)}")

# Display meaningful content after stopword removal
print(f"\nMeaningful words (NLTK): {', '.join(filtered_words_nltk)}")
print(f"Meaningful words (spaCy): {', '.join(filtered_words_spacy)}")
